### ISSUE TITLE
Größer als Epsilon anstatt größer als 0

### ISSUE THREAD

**Issue by Lenaw123** [jfuwien/infstat#2]
Bei der Definition der Konsistenz  auf Seite 31: Muss es  eigentlich heißen P(...> Epsilon) anstatt P(...>0).
>0 ist natürlich auch richtig, da Epsilon>0 ist, aber hat nicht besonders viel Aussagekraft.

**Comment by jfuwien** [comment]
Stimmt natürlich! Danke :)
Ich habe den Fehler bereits in der tex-Datei korrigiert, am Freitag wird dann die neue Pdf mit der Vorlesung von übermorgen und der Korrektur von der Definition hochgeladen.
