### ISSUE TITLE
korollar 3.1

### ISSUE THREAD

**Issue by seungchanwien** [jfuwien/infstat#7]
Korollar 3.1 mu element von (-inf, m_0)

**Comment by jfuwien** [comment]
$\mu_0$ verstehe ich, aber warum sollte \mu_0 nicht mit eingeschlossen sein? 
für mich wäre es \mu\in(-inf,\mu_0] oder?
![image](https://user-images.githubusercontent.com/61250265/123232978-f5b1e400-d4d9-11eb-9d80-4d3ad494df5d.png)

**Comment by seungchanwien** [comment]
ja danke! da war ich schlampig

**Comment by jfuwien** [comment]
Kp, danke fürs Feedback :) [closed](https://github.com/jfuwien/infstat/releases/tag/v.0.3.6)
